{
 "title": "Queue Manager Status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ibmmq_qmgr_status+0" },
    {
     "expr": "ibmmq_qmgr_channel_initiator_status+0"
    },
    {
     "expr": "ibmmq_qmgr_command_server_status+0"
    },
    { "expr": "ibmmq_qmgr_uptime" },
    { "expr": "ibmmq_qmgr_connection_count+0" },
    { "expr": "ibmmq_qmgr_max_channels+0" },
    {
     "expr": "ibmmq_qmgr_max_active_channels+0"
    },
    { "expr": "ibmmq_qmgr_active_listeners+0" }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "targets": [
    { "expr": "ibmmq_cluster_suspend", "legendFormat": "State" }
   ]
  },
  {
   "title": "Connection Count (inc. internal processes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ibmmq_qmgr_connection_count", "legendFormat": "Connection Count: {{qmgr}}" }
   ]
  },
  {
   "title": "Put/Get Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 5 },
   "targets": [
    {
     "expr": "rate(ibmmq_qmgr_interval_mqput_mqput1_total_count[$__rate_interval])",
     "legendFormat": "Puts: {{qmgr}}"
    },
    {
     "expr": "rate(ibmmq_qmgr_interval_destructive_get_total_count[$__rate_interval])",
     "legendFormat": "Gets: {{qmgr}}"
    }
   ]
  },
  {
   "title": "Processed Publications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_exporter_publications",
     "legendFormat": "{{qmgr}}"
    }
   ]
  },
  {
   "title": "FDC Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ibmmq_qmgr_mq_fdc_file_count" }
   ]
  },
  {
   "title": "Native HA",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "ibmmq_nha_backlog_average_bytes",
     "legendFormat": "Backlog average {{qmgr}}/{{nha}}"
    },
    {
     "expr": "ibmmq_nha_synchronous_log_sent_bytes",
     "legendFormat": "Sync bytes sent {{qmgr}}/{{nha}}"
    }
   ]
  }
 ]
}